Support Cave Story: Tweaked as an export
cave-story-randomizer/cave-story-randomizer pull request #173
Opened 2024-01-09 22:32 UTC by calvarado194

Bundled a copy of CSTweaked version 1.5 release candidate. Moved the original pre_Edited_cs folder contents into pre_edited_cs/freeware. Modified patcher function to include the upscaled mychar files provided by Lethrys (these assets have been added to a randovania build which has a separate PR).

2024-01-12 03:28 UTC, duncathan requested changes

2024-01-12 03:28 UTC, duncathan commented on caver/patcher.py
> +def patch_files(patch_data: dict, output_dir: Path, platform: str, progress_update: Callable[[str, float], None]):
you know what, I think the `CSPlatform` enum should be defined in this repo instead, and imported in RDV. much cleaner than using magic strings

2024-01-12 03:28 UTC, duncathan commented on caver/patcher.py
> +    patch_mychar(patch_data["mychar"], output_dir, patch_data["platform"] == "tweaked")
then instead of this expression, you can make 2x mychar a property on the enum itself

2024-01-12 03:28 UTC, duncathan commented on pre_edited_cs/tweaked/data/patcher_data.json
> +{
this file certainly shouldn't be tracked

2024-01-12 03:28 UTC, duncathan commented on pre_edited_cs/tweaked/data/stageconv.exe
what's this for?

2024-01-13 21:34 UTC, calvarado194 commented on pre_edited_cs/tweaked/data/stageconv.exe
I actually should ask you about it! I copied this from the bundled `pre_edited_cs/data` folder, and included it because I assumed it was important.

2024-01-28 00:32 UTC, duncathan approved these changes
im gonna trust you that this didn't break anything ok ema

2024-01-28 00:33 UTC, merged